/**
 * @fileoverview Prompt Generation Contract - Grok vision API integration for card prompts
 * @purpose Define the seam between application (with reference images + style) and Grok vision API
 * @dataFlow Reference Images + Style Inputs → Grok vision-beta API → 22 Card Prompts
 * @boundary Seam #3: PromptGenerationSeam - Generate 22 Major Arcana card prompts using AI
 * @requirement PRD Section: "User Flow Step 3 - Generate Card Prompts"
 * @updated 2025-11-07
 * 
 * @example
 * ```typescript
 * const result = await promptService.generatePrompts({
 *   referenceImageUrls: ['https://...', 'https://...'],
 *   styleInputs: { theme: 'Cyberpunk', tone: 'Dark', ... },
 *   model: 'grok-vision-beta'
 * });
 * 
 * if (result.success) {
 *   const prompts = result.data.cardPrompts; // 22 prompts
 *   const cost = result.data.usage.estimatedCost;
 * }
 * ```
 */

import type { ServiceResponse } from './types/common'
import type { StyleInputs } from './StyleInput'

// ============================================================================
// CONSTANTS
// ============================================================================

/**
 * Grok model names
 */
export const GROK_MODELS = {
  vision: 'grok-vision-beta',
  reasoning: 'grok-beta',
} as const

/**
 * Number of Major Arcana cards
 */
export const MAJOR_ARCANA_COUNT = 22

/**
 * API timeout settings
 */
export const API_TIMEOUT = {
  promptGeneration: 60000, // 60 seconds for generating 22 prompts
  retryDelay: 2000,        // 2 seconds between retries
  maxRetries: 3,           // Maximum retry attempts
} as const

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

/**
 * Grok model type (derived from constant)
 */
export type GrokModel = typeof GROK_MODELS[keyof typeof GROK_MODELS]

/**
 * Major Arcana card numbers (0-21)
 */
export type CardNumber = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 
                         12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21

/**
 * Branded type for prompt IDs
 */
export type PromptId = string & { readonly __brand: 'PromptId' }

// ============================================================================
// MAJOR ARCANA CARD DATA
// ============================================================================

/**
 * Major Arcana card names in order (0-21)
 */
export const MAJOR_ARCANA_NAMES = [
  'The Fool',
  'The Magician',
  'The High Priestess',
  'The Empress',
  'The Emperor',
  'The Hierophant',
  'The Lovers',
  'The Chariot',
  'Strength',
  'The Hermit',
  'Wheel of Fortune',
  'Justice',
  'The Hanged Man',
  'Death',
  'Temperance',
  'The Devil',
  'The Tower',
  'The Star',
  'The Moon',
  'The Sun',
  'Judgement',
  'The World',
] as const

/**
 * Traditional meanings for each Major Arcana card
 * Used to guide AI prompt generation
 */
export const MAJOR_ARCANA_MEANINGS: Record<CardNumber, string> = {
  0: 'New beginnings, innocence, spontaneity, free spirit',
  1: 'Manifestation, resourcefulness, power, inspired action',
  2: 'Intuition, sacred knowledge, divine feminine, subconscious',
  3: 'Femininity, beauty, nature, nurturing, abundance',
  4: 'Authority, establishment, structure, father figure',
  5: 'Spiritual wisdom, religious beliefs, conformity, tradition',
  6: 'Love, harmony, relationships, values alignment, choices',
  7: 'Control, willpower, success, action, determination',
  8: 'Strength, courage, persuasion, influence, compassion',
  9: 'Soul searching, introspection, inner guidance, solitude',
  10: 'Good luck, karma, life cycles, destiny, turning point',
  11: 'Justice, fairness, truth, cause and effect, law',
  12: 'Pause, surrender, letting go, new perspective',
  13: 'Endings, change, transformation, transition',
  14: 'Balance, moderation, patience, purpose',
  15: 'Shadow self, attachment, addiction, restriction',
  16: 'Sudden change, upheaval, chaos, revelation, awakening',
  17: 'Hope, faith, purpose, renewal, spirituality',
  18: 'Illusion, fear, anxiety, subconscious, intuition',
  19: 'Positivity, fun, warmth, success, vitality',
  20: 'Judgement, rebirth, inner calling, absolution',
  21: 'Completion, integration, accomplishment, travel',
}

// ============================================================================
// CORE DATA STRUCTURES
// ============================================================================

/**
 * A single card prompt generated by Grok
 * 
 * @property id - Unique identifier for this prompt
 * @property cardNumber - Card number (0-21)
 * @property cardName - Traditional card name
 * @property traditionalMeaning - Traditional symbolic meaning
 * @property generatedPrompt - AI-generated image generation prompt
 * @property confidence - AI confidence score (0-1)
 * @property generatedAt - Timestamp when prompt was generated
 */
export interface CardPrompt {
  id: PromptId
  cardNumber: CardNumber
  cardName: string
  traditionalMeaning: string
  generatedPrompt: string
  confidence: number
  generatedAt: Date
}

/**
 * API usage and cost tracking
 * 
 * @property promptTokens - Input tokens used
 * @property completionTokens - Output tokens used
 * @property totalTokens - Total tokens used
 * @property estimatedCost - Estimated cost in USD
 * @property model - Model used for generation
 */
export interface ApiUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
  estimatedCost: number
  model: GrokModel
}

/**
 * Progress update during prompt generation
 * 
 * @property status - Current status message
 * @property progress - Progress percentage (0-100)
 * @property currentStep - Current operation step
 */
export interface GenerationProgress {
  status: string
  progress: number
  currentStep: 'uploading' | 'analyzing' | 'generating' | 'validating' | 'complete'
}

// ============================================================================
// INPUT CONTRACTS
// ============================================================================

/**
 * Input for generating card prompts
 * 
 * @property referenceImageUrls - Public URLs of reference images (from Vercel Blob/Cloudinary)
 * @property styleInputs - User-defined style parameters
 * @property model - Grok model to use (defaults to grok-vision-beta)
 * @property temperature - Generation temperature (0-2, default 0.8)
 * @property onProgress - Optional callback for progress updates
 */
export interface GeneratePromptsInput {
  referenceImageUrls: string[]
  styleInputs: StyleInputs
  model?: GrokModel
  temperature?: number
  onProgress?: (progress: GenerationProgress) => void
}

/**
 * Input for validating generated prompts
 * 
 * @property prompts - Prompts to validate
 */
export interface ValidatePromptsInput {
  prompts: CardPrompt[]
}

/**
 * Input for regenerating a single prompt
 * 
 * @property cardNumber - Card to regenerate
 * @property referenceImageUrls - Reference image URLs
 * @property styleInputs - Style parameters
 * @property previousPrompt - Previous prompt to improve upon
 * @property feedback - Optional user feedback for regeneration
 */
export interface RegeneratePromptInput {
  cardNumber: CardNumber
  referenceImageUrls: string[]
  styleInputs: StyleInputs
  previousPrompt?: string
  feedback?: string
}

/**
 * Input for editing a generated prompt
 * 
 * @property promptId - ID of prompt to edit
 * @property editedPrompt - New prompt text
 */
export interface EditPromptInput {
  promptId: PromptId
  editedPrompt: string
}

// ============================================================================
// OUTPUT CONTRACTS
// ============================================================================

/**
 * Result of generating prompts
 * 
 * @property cardPrompts - All 22 generated prompts
 * @property usage - API usage and cost information
 * @property requestId - Grok API request ID for debugging
 * @property generatedAt - Timestamp of generation
 * @property model - Model used
 */
export interface GeneratePromptsOutput {
  cardPrompts: CardPrompt[]
  usage: ApiUsage
  requestId: string
  generatedAt: Date
  model: GrokModel
}

/**
 * Result of validating prompts
 * 
 * @property isValid - Whether all prompts are valid
 * @property invalidPrompts - Prompts that failed validation
 * @property errors - Validation errors
 */
export interface ValidatePromptsOutput {
  isValid: boolean
  invalidPrompts: CardPrompt[]
  errors: PromptValidationError[]
}

/**
 * Result of regenerating a single prompt
 * 
 * @property cardPrompt - New prompt for the card
 * @property usage - API usage for this regeneration
 * @property requestId - Grok API request ID
 */
export interface RegeneratePromptOutput {
  cardPrompt: CardPrompt
  usage: ApiUsage
  requestId: string
}

/**
 * Result of editing a prompt
 * 
 * @property cardPrompt - Updated prompt
 * @property edited - Whether edit was successful
 */
export interface EditPromptOutput {
  cardPrompt: CardPrompt
  edited: boolean
}

// ============================================================================
// ERROR CODES
// ============================================================================

/**
 * All possible error codes for prompt generation operations
 */
export enum PromptGenerationErrorCode {
  // API errors
  API_KEY_MISSING = 'API_KEY_MISSING',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_TIMEOUT = 'API_TIMEOUT',
  API_RATE_LIMIT = 'API_RATE_LIMIT',
  API_ERROR = 'API_ERROR',
  
  // Input validation
  NO_REFERENCE_IMAGES = 'NO_REFERENCE_IMAGES',
  INVALID_REFERENCE_URL = 'INVALID_REFERENCE_URL',
  INVALID_STYLE_INPUTS = 'INVALID_STYLE_INPUTS',
  INVALID_MODEL = 'INVALID_MODEL',
  
  // Response validation
  INCOMPLETE_RESPONSE = 'INCOMPLETE_RESPONSE',      // Received <22 prompts
  INVALID_RESPONSE_FORMAT = 'INVALID_RESPONSE_FORMAT', // JSON parse error
  PROMPT_TOO_SHORT = 'PROMPT_TOO_SHORT',
  PROMPT_TOO_LONG = 'PROMPT_TOO_LONG',
  DUPLICATE_CARD_NUMBER = 'DUPLICATE_CARD_NUMBER',
  MISSING_CARD_NUMBER = 'MISSING_CARD_NUMBER',
  
  // Network errors
  NETWORK_ERROR = 'NETWORK_ERROR',
  IMAGE_URL_UNREACHABLE = 'IMAGE_URL_UNREACHABLE',
  
  // Cost/quota errors
  INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
}

/**
 * Validation error for a prompt
 */
export interface PromptValidationError {
  code: PromptGenerationErrorCode
  message: string
  cardNumber?: CardNumber
  promptId?: PromptId
}

// ============================================================================
// SERVICE INTERFACE (THE CONTRACT)
// ============================================================================

/**
 * Prompt Generation Service Contract
 * 
 * Defines all operations for generating tarot card prompts using Grok vision API.
 * Implementation handles:
 * - Reference image upload to temporary storage
 * - Grok vision API calls with images + style parameters
 * - Response parsing and validation (22 prompts)
 * - Cost calculation and tracking
 * - Progress updates during generation
 * - Prompt regeneration and editing
 * 
 * @interface IPromptGenerationService
 */
export interface IPromptGenerationService {
  /**
   * Generate all 22 Major Arcana card prompts
   * 
   * Workflow:
   * 1. Upload reference images to Vercel Blob/Cloudinary (get public URLs)
   * 2. Call Grok vision API with images + style parameters
   * 3. Parse response into 22 CardPrompt objects
   * 4. Validate prompts (completeness, card numbers, etc.)
   * 5. Calculate usage and cost
   * 6. Delete temporary image uploads
   * 
   * @param input - Reference images, style inputs, and options
   * @returns Promise<ServiceResponse<GeneratePromptsOutput>> - 22 prompts
   * 
   * @throws Never throws - all errors returned in ServiceResponse
   * 
   * @example
   * ```typescript
   * const result = await service.generatePrompts({
   *   referenceImageUrls: ['https://blob.vercel-storage.com/...'],
   *   styleInputs: {
   *     theme: 'Cyberpunk',
   *     tone: 'Dark',
   *     description: 'Neon-lit dystopian future...'
   *   },
   *   onProgress: (progress) => {
   *     console.log(`${progress.status}: ${progress.progress}%`);
   *   }
   * });
   * 
   * if (result.success) {
   *   console.log(`Generated ${result.data.cardPrompts.length} prompts`);
   *   console.log(`Cost: $${result.data.usage.estimatedCost}`);
   * }
   * ```
   */
  generatePrompts(
    input: GeneratePromptsInput
  ): Promise<ServiceResponse<GeneratePromptsOutput>>

  /**
   * Validate generated prompts
   * 
   * Checks that:
   * - Exactly 22 prompts
   * - All card numbers 0-21 present
   * - No duplicate card numbers
   * - All prompts have reasonable length
   * - All required fields present
   * 
   * @param input - Prompts to validate
   * @returns Promise<ServiceResponse<ValidatePromptsOutput>> - Validation results
   * 
   * @throws Never throws - all errors returned in ServiceResponse
   * 
   * @example
   * ```typescript
   * const result = await service.validatePrompts({ prompts });
   * if (!result.data.isValid) {
   *   console.error('Validation errors:', result.data.errors);
   * }
   * ```
   */
  validatePrompts(
    input: ValidatePromptsInput
  ): Promise<ServiceResponse<ValidatePromptsOutput>>

  /**
   * Regenerate a single card prompt
   * 
   * Useful when user is unsatisfied with a specific prompt.
   * Can include feedback to guide regeneration.
   * 
   * @param input - Card to regenerate and context
   * @returns Promise<ServiceResponse<RegeneratePromptOutput>> - New prompt
   * 
   * @throws Never throws - all errors returned in ServiceResponse
   * 
   * @example
   * ```typescript
   * const result = await service.regeneratePrompt({
   *   cardNumber: 0, // The Fool
   *   referenceImageUrls: [...],
   *   styleInputs: {...},
   *   previousPrompt: 'Original prompt...',
   *   feedback: 'Make it more mysterious'
   * });
   * 
   * if (result.success) {
   *   replacePrompt(0, result.data.cardPrompt);
   * }
   * ```
   */
  regeneratePrompt(
    input: RegeneratePromptInput
  ): Promise<ServiceResponse<RegeneratePromptOutput>>

  /**
   * Edit a generated prompt manually
   * 
   * Allows user to manually refine AI-generated prompt.
   * Validates edited prompt length and format.
   * 
   * @param input - Prompt ID and new text
   * @returns Promise<ServiceResponse<EditPromptOutput>> - Updated prompt
   * 
   * @throws Never throws - all errors returned in ServiceResponse
   * 
   * @example
   * ```typescript
   * const result = await service.editPrompt({
   *   promptId: 'prompt-uuid-123',
   *   editedPrompt: 'Cyberpunk character with neon implants...'
   * });
   * 
   * if (result.success) {
   *   updateUI(result.data.cardPrompt);
   * }
   * ```
   */
  editPrompt(
    input: EditPromptInput
  ): Promise<ServiceResponse<EditPromptOutput>>

  /**
   * Get estimated cost for prompt generation
   * 
   * Calculates estimated cost based on:
   * - Number of reference images
   * - Style input length
   * - Expected output tokens (22 prompts)
   * 
   * @param input - Reference images and style inputs
   * @returns Promise<ServiceResponse<ApiUsage>> - Cost estimate
   * 
   * @throws Never throws - all errors returned in ServiceResponse
   * 
   * @example
   * ```typescript
   * const result = await service.estimateCost({
   *   referenceImageUrls: [...],
   *   styleInputs: {...}
   * });
   * 
   * if (result.success) {
   *   if (result.data.estimatedCost > 1.00) {
   *     confirmWithUser(`This will cost $${result.data.estimatedCost}`);
   *   }
   * }
   * ```
   */
  estimateCost(
    input: Omit<GeneratePromptsInput, 'onProgress'>
  ): Promise<ServiceResponse<ApiUsage>>
}

// ============================================================================
// USER-FRIENDLY ERROR MESSAGES
// ============================================================================

/**
 * Maps error codes to user-friendly messages
 */
export const PROMPT_GENERATION_ERROR_MESSAGES: Record<PromptGenerationErrorCode, string> = {
  [PromptGenerationErrorCode.API_KEY_MISSING]: 
    'Grok API key is not configured - please contact support',
  [PromptGenerationErrorCode.API_KEY_INVALID]: 
    'Grok API key is invalid - please contact support',
  [PromptGenerationErrorCode.API_TIMEOUT]: 
    'Request timed out - please try again',
  [PromptGenerationErrorCode.API_RATE_LIMIT]: 
    'Too many requests - please wait a moment and try again',
  [PromptGenerationErrorCode.API_ERROR]: 
    'Grok API error - please try again',
  
  [PromptGenerationErrorCode.NO_REFERENCE_IMAGES]: 
    'No reference images provided',
  [PromptGenerationErrorCode.INVALID_REFERENCE_URL]: 
    'Reference image URL is invalid or unreachable',
  [PromptGenerationErrorCode.INVALID_STYLE_INPUTS]: 
    'Style inputs are invalid',
  [PromptGenerationErrorCode.INVALID_MODEL]: 
    'Invalid Grok model specified',
  
  [PromptGenerationErrorCode.INCOMPLETE_RESPONSE]: 
    'Generated fewer than 22 prompts - please try again',
  [PromptGenerationErrorCode.INVALID_RESPONSE_FORMAT]: 
    'Invalid response format from Grok - please try again',
  [PromptGenerationErrorCode.PROMPT_TOO_SHORT]: 
    'Generated prompt is too short',
  [PromptGenerationErrorCode.PROMPT_TOO_LONG]: 
    'Generated prompt exceeds maximum length',
  [PromptGenerationErrorCode.DUPLICATE_CARD_NUMBER]: 
    'Duplicate card number in response',
  [PromptGenerationErrorCode.MISSING_CARD_NUMBER]: 
    'Missing card number in response',
  
  [PromptGenerationErrorCode.NETWORK_ERROR]: 
    'Network error - please check your connection',
  [PromptGenerationErrorCode.IMAGE_URL_UNREACHABLE]: 
    'Reference image cannot be accessed',
  
  [PromptGenerationErrorCode.INSUFFICIENT_CREDITS]: 
    'Insufficient API credits - please contact support',
  [PromptGenerationErrorCode.QUOTA_EXCEEDED]: 
    'API quota exceeded - please try again later',
}

// ============================================================================
// METADATA
// ============================================================================

/**
 * Contract metadata for tracking and documentation
 */
export const PROMPT_GENERATION_CONTRACT_METADATA = {
  version: '1.0.0',
  seam: 'PromptGenerationSeam',
  boundary: 'Application → Grok Vision API',
  requirement: 'PRD: User Flow Step 3',
  lastUpdated: '2025-11-07',
  dependencies: ['StyleInput'],
  externalAPIs: ['Grok vision-beta'],
} as const
